version: 1.2
workflows:
- name: main
  primaryDescriptorPath: /Galaxy-Workflow-Meryl_Database_Creation.ga
  subclass: Galaxy
  testParameterFiles:
  - /Galaxy-Workflow-Meryl_Database_Creation-tests.yml
